// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqYuKvpsS4XA6wGfd9t1mIQGJBnMJXkbA',
    appId: '1:975102948364:android:dce6331667364b475aaa29',
    messagingSenderId: '975102948364',
    projectId: 'evently-app-alaamahmoud',
    storageBucket: 'evently-app-alaamahmoud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBVcjYX3jRT-gw6HUXTRk5fqEHocZJ6M',
    appId: '1:975102948364:ios:61c1fed9b302172b5aaa29',
    messagingSenderId: '975102948364',
    projectId: 'evently-app-alaamahmoud',
    storageBucket: 'evently-app-alaamahmoud.firebasestorage.app',
    androidClientId: '975102948364-a91pq0q0lghcdcelojlp17pat80tfphu.apps.googleusercontent.com',
    iosClientId: '975102948364-8hhkfl9kqdk9qlhpi7j63jlh5gdnh5rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

}